let i=2;

function displayNone() {
    document.getElementById('login').style.display = "none";
}
function nextip() {
    id='opt'+i;
    document.getElementById(id).next().focus();
    i++;
}
function login(){
    document.getElementById('login').style.display = "block";
    document.getElementById('login').innerHTML='<img id="back" src="Images/Back.png" alt=""><div class="box center"><span class="arrow" onclick="displayNone()">&#8592;</span><img src="Images/Logo.png" alt="Craftoza" class="center logo"><p class="head bolder">LOGIN</p><form action="" method="post" class="center2"><label for="Email">Email</label><br><input type="email" id="email" name="Email" value="" class="inp"><br><label for="Password">Password</label><br><input type="password" id="password" name="Password" value="" class="inp"><br><br><input type="checkbox" name="Remember_me" id="remember_me"><label for="Remember_me" style="font-size: 14px;">Remember Me?</label><br><br><input type="submit" value="LOGIN" class="button2" onclick="displayNone()"><p style="font-size: 14px; padding-left: 75px;"><span onclick="forgotpwd()">Forgot Password</span></p><br><br></form><p style="font-size: 14px; padding-bottom: 40px;">Need an Account? <span style="font-size: 14px;" onclick="sign()">SIGN UP</span></p></div>'
}
function sign(){
    document.getElementById('login').innerHTML='<img id="back" src="Images/Back.png" alt=""><div class="box center"><span class="arrow" onclick="displayNone()">&#8592;</span><img src="Images/Logo.png" alt="Craftoza" class="center logo"><p class="head bolder">SIGNUP</p><form action="" method="post" class="center2"><label for="Email">Email</label><br><input type="email" id="email" name="Email" value="" class="inp"><br><label for="Password" class="bolder">Password</label><br><input type="password" id="password" name="Password" value="" class="inp"><br><label for="ConfirmPassword" class="bolder">Confirm Password</label><br><input type="password" id="confirmpassword" name="ConfirmPassword" value="" class="inp"><br><br><input type="submit" value="SIGNUP" class="button2" onclick="displayNone()"><br><br></form><p style="font-size: 14px; padding-bottom: 40px;">Already have an Account? <span style="font-size: 14px; display: inline-block;" onclick="login()">LOG IN</span></p></div>'
}
function forgotpwd(){
    document.getElementById('login').innerHTML='<img id="back" src="Images/Back.png" alt=""><div class="box center" style="top:23vh;"><span class="arrow" onclick="displayNone()">&#8592;</span><img src="Images/Logo.png" alt="Craftoza" class="center logo"><p class="head bolder" style="font-size: x-large;">FORGOT PASSWORD?</p><form action="" method="post" class="center2"><br><label for="Email">Email</label><br><input type="email" id="email" name="Email" value="" class="inp"><br><!-- <label for="Password">Password</label><br><input type="password" id="password" name="Password"  value="" class="inp"><br><br><input type="checkbox" name="Remember_me" id="remember_me"><label for="Remember_me" style="font-size: 14px;">Remember Me?</label> --><br><input type="button" value="GET OTP" class="button2"onclick="gotp()"><br><br></form><p style="font-size: 14px; padding-bottom: 40px; padding-left: 75px;"><span onclick="login()">Back to Log In?</span></p></div>'
}
function gotp(){
    document.getElementById('login').innerHTML='<img id="back" src="Images/Back.png" alt=""><div class="box center"><span class="arrow" onclick="displayNone()">&#8592;</span><img src="Images/Logo.png" alt="Craftoza" class="center logo"><img src="Images/VALIDATE.png" alt="Email icon" class="center" style="width:20%;height:20%"><p style="font-size: large;">Please Enter The OTP To Verify Your Account</p><p style="font-size: medium; color: rgb(44, 43, 43);">An OPT Has Been Sent To <span id="putemail">(Email)</span></p><form action="" method="post" class="center2"><br><br><input type="text" id="otp" name="opt" value="" maxlength="6" oninput="this.value=this.value.replace(/[^0-9]/g,"")" class="otpinp"><br><br><input type="button" value="VERIFY" class="button2" onclick="npwd()"><br><br></form><p style="font-size: 14px; padding-bottom: 10px;"><span>RESEND OTP</span></p><p style="font-size: 14px; padding-bottom: 40px;"><span onclick="forgotpwd()">INVALID EMAIL?</span></p></div><br>'
}
function npwd(){
    document.getElementById('login').innerHTML='<img id="back" src="Images/Back.png" alt=""><div class="box center" style="top:22vh;"><span class="arrow" onclick="displayNone()">&#8592;</span><img src="Images/Logo.png" alt="Craftoza" class="center logo"><p class="head bolder">NEW PASSWORD</p><form action="" method="post" class="center2"><label for="Password" class="bolder">Password</label><br><input type="password" id="password" name="Password" value="" class="inp"><br><label for="ConfirmPassword" class="bolder">Confirm Password</label><br><input type="password" id="confirmpassword" name="ConfirmPassword" value="" class="inp"><br><br><input type="button" value="SUBMIT" class="button2" onclick="displayNone()"><br><br><br><br></form></div>'
}